### ISSUE TITLE
Installation fails with import errors

### ISSUE THREAD

**Issue by sshine** [exercism/exalysis#80]
When following the [installation instructions](https://github.com/tehsphinx/exalysis/#installation), I get the following result:

    $ go get github.com/tehsphinx/exalysis
    # golang.org/x/tools/go/internal/gcimporter
    ../go/src/golang.org/x/tools/go/internal/gcimporter/bexport.go:212:
        obj.IsAlias undefined (type *types.TypeName has no field or method IsAlias)

I've never written anything in Go, so I don't know how to proceed.

Am I (and the installation instructions) missing something crucial that a Go programmer takes for granted?

    $ go version
    go version go1.8.3 linux/amd64

On Linux 4.13.0, x86_64.

**Comment by tehsphinx** [comment]
The go version might be too old. I am currently on `go version go1.11.5 darwin/amd64`. Additionally this uses `go modules` for dependency management which are only available since `go1.11`.

Once you installed go 1.11.x try this to make sure `go modules` is used:

```
env GO111MODULE=on go get github.com/tehsphinx/exalysis
```

Let me know if that helps.

**Comment by bitfield** [comment]
> Am I missing something crucial that a Go programmer takes for granted?

About two years.
