### ISSUE TITLE
twofer: additional suggestions

### ISSUE THREAD

**Issue by tehsphinx** [exercism/exalysis#81]
There are 2 things I am thinking of adding:

* introducing an extra variable on `twofer` is not necessary in Go as Go does not pass by reference. A hint on that and an explanation might be useful if people add a new variable instead of overwriting `name` if it is empty.
* I have seen solutions using an additional function which makes it only harder to read. A Comment might be useful to point that out.
* EDIT: check for `len(name) != 0` comparison. A string in Go should be checked with `name == ""` for emptiness since a string in Go cannot be `nil` -- or anything else.

https://github.com/exercism/automated-mentoring-support/issues/4

**Comment by bitfield** [comment]
Good idea! I never understood why people seem so reluctant to assign to the `name` variable; if they come from pass-by-reference languages that might explain it.

**Comment by tehsphinx** [comment]
All 3 points added to `go-analyzer` repo (not uploaded yet: see https://github.com/exercism/automated-mentoring-support/issues/17).

TODO: Need to switch exalysis over use the suggestion algorithm from `go-analyzer` once everything is integrated there.

**Comment by tehsphinx** [comment]
`exalysis` now uses the same suggestion algorithm as `go-analyzer` for `two-fer`
