### ISSUE TITLE
Mac Install

### ISSUE THREAD

**Issue by LucaPaterlini** [exercism/exalysis#98]
Hello I was just trying to use exalysis on a macgo 1.15.1

GO111MODULE=on go get -u github.com/exercism/exalysis

# github.com/exercism/exalysis/exam
../pkg/mod/github.com/exercism/exalysis@v0.4.7/exam/gobench.go:23:26: not enough arguments in call to aurora.Gray
	have (string)
	want (uint8, interface {})
../pkg/mod/github.com/exercism/exalysis@v0.4.7/exam/gobench.go:30:26: not enough arguments in call to aurora.Gray
	have (string)
	want (uint8, interface {})
../pkg/mod/github.com/exercism/exalysis@v0.4.7/exam/gobench.go:32:26: not enough arguments in call to aurora.Gray
	have (string)
	want (uint8, interface {})
../pkg/mod/github.com/exercism/exalysis@v0.4.7/exam/gofmt.go:21:26: not enough arguments in call to aurora.Gray
	have (string)
	want (uint8, interface {})
../pkg/mod/github.com/exercism/exalysis@v0.4.7/exam/golangci-lint.go:20:26: not enough arguments in call to aurora.Gray
	have (string)
	want (uint8, interface {})
../pkg/mod/github.com/exercism/exalysis@v0.4.7/exam/golangci-lint.go:26:26: not enough arguments in call to aurora.Gray
	have (string)
	want (uint8, interface {})
../pkg/mod/github.com/exercism/exalysis@v0.4.7/exam/golangci-lint.go:30:25: not enough arguments in call to aurora.Gray
	have (string)
	want (uint8, interface {})
../pkg/mod/github.com/exercism/exalysis@v0.4.7/exam/golint.go:24:26: not enough arguments in call to aurora.Gray
	have (string)
	want (uint8, interface {})
../pkg/mod/github.com/exercism/exalysis@v0.4.7/exam/golint.go:34:25: not enough arguments in call to aurora.Gray
	have (string)
	want (uint8, interface {})
../pkg/mod/github.com/exercism/exalysis@v0.4.7/exam/gotest.go:40:26: not enough arguments in call to aurora.Gray
	have (string)
	want (uint8, interface {})
../pkg/mod/github.com/exercism/exalysis@v0.4.7/exam/gotest.go:40:26: too many errors

**Comment by LucaPaterlini** [comment]
tried again

Luca.Paterlini@MC02D1288MD6R ~ % cd $GOPATH  
Luca.Paterlini@MC02D1288MD6R go % GO111MODULE=on go get github.com/exercism/exalysis
GO111MODULE=on go install github.com/exercism/exalysis/cmd/exalysis
go: github.com/exercism/exalysis upgrade => v0.4.7
cannot find module providing package github.com/exercism/exalysis/cmd/exalysis: working directory is not part of a module

**Comment by LucaPaterlini** [comment]
Third attempt

cd $GOPATH
Luca.Paterlini@MC02D1288MD6R go % ls
bin	pkg	src	temp
Luca.Paterlini@MC02D1288MD6R go % cd temp 
Luca.Paterlini@MC02D1288MD6R temp % ls
go.mod	go.sum
Luca.Paterlini@MC02D1288MD6R temp % go get github.com/exercism/exalysis
Luca.Paterlini@MC02D1288MD6R temp % go install github.com/exercism/exalysis/cmd/exalysis
Luca.Paterlini@MC02D1288MD6R temp % exalysis
zsh: command not found: exalysis
Luca.Paterlini@MC02D1288MD6R temp % cat ~/.zshrc     
PATH=$PATH:/Users/Luca.Paterlini/Library/Python/3.8/bin
export GOPATH=$HOME/go

**Comment by tehsphinx** [comment]
We should update the installation instructions, yes.

We should be able to remove the `GO111MODULE=on` part. And maybe mention to add `$GOPATH/bin` to the $PATH, so exalysis can be executed from anywhere.

Any other insights we should add? @LucaPaterlini?

Note: first try you added `-u` parameter. That will update all dependencies potentially creating incompatibilities.

**Comment by LucaPaterlini** [comment]
I tried both, the one shown here
and the one from the instructions.
Same results,
I have no better insights

**Comment by tehsphinx** [comment]
Problem is you have to be inside a go module. Any path inside a go module will do to run `go install`. If you have none on your computer try `go mod init someModule` first.

**Comment by tehsphinx** [comment]
Then after you actually can run the `go install` command directly (I think).

**Comment by tehsphinx** [comment]
@LucaPaterlini: I updated the installation instructions here: https://github.com/exercism/exalysis/blob/master/README.md

Can you let me know if that works for you?

**Comment by LucaPaterlini** [comment]
I have entered the folder of one of the exercises and done the new command,
now it works, thanks
